### ISSUE TITLE
Error in manifest (Puppet 2.7.18 / Debian Squeeze)

### ISSUE THREAD

**Issue by damiencorpataux** [AlexCline/puppet-fstab#1]
Hi, I get the following error when using this module with Puppet 2.7.18 on Debian Squeeze:

**err: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function error at /etc/puppet/modules/fstab/manifests/init.pp:38 on node puppet**

**Comment by AlexCline** [comment]
Thanks for the bug report.  I haven't tested the module on Debian, so as of right now there is a case that restricts the module to centos/redhat/amazon only.  I don't have any Debian systems that I can test on at the moment, but if you'd like to remove/fix the case to test, I would appreciate it.

I'll update the code to use the 'err' function correctly so an error is logged when trying to use the module on a different platform.

Hopefully I'll have some time soon to test on other platforms.

**Comment by AlexCline** [comment]
Commit d5fae2304 fixes this error.
