### ISSUE TITLE
changing source results in new entry

### ISSUE THREAD

**Issue by simoncrute** [AlexCline/puppet-fstab#3]
Hi, 
I'm using the fstab module, but if I change the Source defination for a fstab entry, it creates a new line in fstab. 

There needs to be a way if indicating if existing entries should be unique for source (i.e. changing the mount point of a source) or unique for destination (i.e. changing where a filesystem is mounted from) 

Thanks.

**Comment by AlexCline** [comment]
In commit 0261b0cf3b I've changed the name of the subresources created by the fstab module.  They were being created based off of the attribute's of the resource.  They're now created using the parent's name, so it won't be as verbose, but you should be able to change attributes and have them correctly updated.

I've tested this module and the changes don't cause failures in my environment.  Can you grab the latest module (v 0.3.0) from the forge and test if it works for you?

**Comment by AlexCline** [comment]
I've tested this in my environment and it seems to work.  Please reopen if you encounter issues with the new release.
