### ISSUE TITLE
Where does `concat()` come from?

### ISSUE THREAD

**Issue by sietse** [AlexCline/puppet-fstab#4]
Hi Alex,
I'm trying to find out whether your `fstab` module will work on Debian -- after all, Debian uses the same fstab as Red Hat does. Unfortunately, I get this error:

**Unknown function concat at [...]/.puppet/modules/fstab/manifests/augeas.pp:35**

Lines 34-46:

```
# Concat parts one and two into onetwo, then concat onetwo and three
$fstab_parts_onetwo = concat($fstab_part_one, $fstab_part_two)
$fstab_changes      = concat($fstab_parts_onetwo, $fstab_part_three)
```

This is on a virgin install of Puppet, and a near-virgin install of Linux Mint Debian Edition. Where/how is concat defined in your Puppet?

**Comment by AlexCline** [comment]
The concat function is part of the puppetlabs/stdlib module.  Male sure that module is also installed in your environment.

**Comment by AlexCline** [comment]
My apologies.  It seems the module file doesn't specify the puppetlabs/stdlib module as a dependency.  I'll add it and push an update tonight.
