### ISSUE TITLE
fstab_match_line undefined in augeas.pp and error undefined in init.pp

### ISSUE THREAD

**Issue by qha** [AlexCline/puppet-fstab#9]
I'll try to attach a patch right away.

It also includes fstab::variables from the test manifest as I can't run it otherwise. You might not want to accept the last fstab resource in the test manifest which removes /proc, but I needed it to provoke the error I suspected fstab_match_line missing would cause.

**Comment by qha** [comment]
The preview does not look promising, so apologies for the format of this diff. Suggestions for better ways to send it would be appreciated.

diff --git a/fstab/manifests/augeas.pp b/fstab/manifests/augeas.pp
index 33a78af..013a17d 100644
--- a/fstab/manifests/augeas.pp
+++ b/fstab/manifests/augeas.pp
@@ -8,6 +8,7 @@ define fstab::augeas(
   $dump   = 0,
   $passno = 0,
   $ensure = 'present'){
-  $fstab_match_line = "*[spec='${source}' and file='${dest}']"
  
  case $ensure {
   'present': {
  diff --git a/fstab/manifests/init.pp b/fstab/manifests/init.pp
  index be505e1..8dc5f33 100644
  --- a/fstab/manifests/init.pp
  +++ b/fstab/manifests/init.pp
  @@ -10,15 +10,15 @@ define fstab(
  $ensure = 'present'){
  
  if $source == undef {
-    error('The source parameter is required.')
-    err('The source parameter is required.')
  }
  
  if $dest == undef {
-    error('The dest parameter is required.')
-    err('The dest parameter is required.')
  }
  
  if $type == undef {
-    error('The type parameter is required.')
-    err('The type parameter is required.')
  }
  
  case $::osfamily {
  diff --git a/fstab/tests/init.pp b/fstab/tests/init.pp
  index f954cb9..767ac37 100644
  --- a/fstab/tests/init.pp
  +++ b/fstab/tests/init.pp
  @@ -1,3 +1,5 @@
  +include fstab::variables
  +
  
  # fstab module test resources.
  
  fstab { 'A test fstab entry':
  @@ -48,4 +50,11 @@ fstab {'Revert AWS Root Drive':
  dump    => 0,
  passno  => 0,
  require => Fstab['AWS Root Drive'],
  -}
  \ No newline at end of file
  +}
  +
  +fstab { 'remove proc':
-  ensure => absent,
-  source => 'proc',
-  dest   => '/proc',
-  type   => 'proc',
  +}

**Comment by AlexCline** [comment]
Can you submit this as a pull request?  It'll make it easier for me to review.

Thanks.

**Comment by qha** [comment]
After some trial and error it seems I can.

See: "Repair fstab::augeas for ensure absent."

Thanks for considering this!

**Comment by masimplo** [comment]
This seems as the cause for #13 as well. Any update on this?

**Comment by jgrumboe** [comment]
PR #15 seems more complete for me for the ensure=>absent problem.

**Comment by qha** [comment]
@jgrumboe I haven't run into the issues the other changes address but it does seem to fix my issue. I would still like to see the test manifest amended but i will make a separate pull request for that.
